doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options:
                username: root
                password: example
                authSource: '%env(resolve:MONGODB_DB)%'
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
    hydrator_namespace:   Hydrators
    hydrator_dir:         "%kernel.cache_dir%/doctrine/odm/mongodb/Hydrators"