version: '2'
services:
  paper-rock-scissors:
    image: paperrockscissors/paperrockscissors:dev
    stdin_open: true
    tty: true
    links:
    - mongodb:database
    ports:
    - 8000:80
  mongodb:
    image: mongo:latest
    environment:
      MONGODB_USER: root
      MONGODB_PASS: root
      MONGODB_DB: symfony
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: symfony
    stdin_open: true
    tty: true
    volumes:
      - mongodata:/data/db
    ports:
    - 27017:27017
volumes:
  mongodata: